# Generated by Django 2.2 on 2020-07-30 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200726_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Request Confirmed?')),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='firends_obj',
            field=models.ManyToManyField(blank=True, related_name='friends_obj', through='accounts.FriendThrough', to=settings.AUTH_USER_MODEL),
        ),
    ]
