# Generated by Django 2.2 on 2020-07-30 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200730_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendthrough',
            name='friend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendthrough',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='friendthrough',
            unique_together={('user', 'friend_user')},
        ),
    ]
