# Generated by Django 2.2 on 2020-07-25 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200726_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.CharField(blank=True, choices=[('1st grade', '1st grade'), ('2nd grade', '2nd grade'), ('3rd grade', '3rd grade'), ('4th grade', '4th grade'), ('5th grade', '5th grade'), ('6th grade', '6th grade'), ('7th grade', '7th grade'), ('8th grade', '8th grade'), ('9th grade', '9th grade'), ('9th grade', '9th grade'), ('10th grade', '10th grade')], max_length=10, verbose_name='Grade/Class')),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Section')),
                ('roll_number', models.IntegerField(blank=True, verbose_name='Roll Number of Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTeacherThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starred', models.BooleanField(blank=True, default=False, verbose_name='Is Student Extraordinary?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject', models.CharField(max_length=255, verbose_name='Subjects Tought')),
                ('student_list', models.ManyToManyField(through='home.StudentTeacherThrough', to='home.Student', verbose_name='students objects')),
            ],
        ),
        migrations.AddField(
            model_name='studentteacherthrough',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_list',
            field=models.ManyToManyField(through='home.StudentTeacherThrough', to='home.Teacher', verbose_name='Teacher objects'),
        ),
        migrations.CreateModel(
            name='HeadMaster',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.StudentTeacherThrough')),
            ],
        ),
    ]
