# Generated by Django 2.2 on 2020-07-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_list',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student_list',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_obj',
            field=models.ManyToManyField(through='home.StudentTeacherThrough', to='home.Teacher', verbose_name='My Teachers'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_obj',
            field=models.ManyToManyField(through='home.StudentTeacherThrough', to='home.Student', verbose_name='Student Teaching'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Roll Number of Student'),
        ),
    ]
