# Generated by Django 2.2 on 2020-07-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200726_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_obj',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentteacherthrough',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentteacherthrough',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student_obj',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='HeadMaster',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentTeacherThrough',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
