# Generated by Django 2.2 on 2020-07-30 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200726_0413'),
        ('home', '0004_auto_20200726_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentteacherthrough',
            unique_together={('student', 'teacher', 'headmaster')},
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('user_self', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firends_obj', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Friends')),
            ],
        ),
    ]
