# Generated by Django 2.2 on 2020-07-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200730_0736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
